apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: whanos-name
  name: whanos-name
spec:
  replicas: 1
  selector:
    matchLabels:
      service: whanos-name
  template:
    metadata:
      labels:
        service: whanos-name
    spec:
      containers:
        - name: whanos-name
          image: whanos-img
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 250Mi
      restartPolicy: Always
